### ISSUE TITLE
Пофиксить все .html файлы.

### ISSUE THREAD

**Issue by vsmaxim** [iWasBornInUSSR/dmJS_colloc#2]
1) поменять всё что внутри head на, то что уже в готовых модулях, т.е. привести их к единому виду.
2) добавить перед закрытием body строку `<script src="js/handler.js"></script>`
3) к полю ввода первого числа добавить id = "first", второго "second", третьего third
4) к полю вывода результата добавить id = result
5) В каждый файл в head добавить строки 
```HTML
<script stc="../js/natural.js"></script>
<script stc="../js/integer.js"></script>
<script stc="../js/rational.js"></script>
<script stc="../js/polynome.js"></script>
```
6) На кнопку вычисления добавить `onclick="handler(Название функции)"`, например для ADD_NN_N, нужно добавить `handler(ADD_NN_N)`

**Comment by yummyKnight** [comment]
Сделано
