### ISSUE TITLE
Проблема с парсером многочленов

### ISSUE THREAD

**Issue by yummyKnight** [iWasBornInUSSR/dmJS_colloc#23]
![image](https://user-images.githubusercontent.com/38350199/39013559-610a1dd8-4420-11e8-9125-6805f962b57e.png)

**Comment by yummyKnight** [comment]
Если нет в многочлене нет нулевой степени, то прибавляет к многочлену 1

**Comment by vsmaxim** [comment]
Если в многочлене минус в начале, то добавлялся один, потому что кто-то написал кусок говнокода.
